"""add the 2D Assessment schema foundation

Revision ID: 20260804_0004
Revises: 20260715_0003
Create Date: 2026-08-04
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

revision = "20260804_0004"
down_revision = "20260715_0003"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute('CREATE TABLE assessment_workspaces (\n\tid SERIAL NOT NULL, \n\tsite_id INTEGER NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tUNIQUE (site_id), \n\tFOREIGN KEY(site_id) REFERENCES sites (id) ON DELETE RESTRICT\n)' )
    op.execute("CREATE TABLE project_lines_datasets (\n\tid SERIAL NOT NULL, \n\tworkspace_id INTEGER NOT NULL, \n\tdomain_id VARCHAR(255) NOT NULL, \n\tname VARCHAR(255) NOT NULL, \n\timported_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tsource_file_name VARCHAR(255) NOT NULL, \n\tis_active BOOLEAN NOT NULL, \n\tlines_json JSONB NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_project_lines_datasets_workspace_domain_id UNIQUE (workspace_id, domain_id), \n\tCONSTRAINT ck_project_lines_datasets_lines_json_array CHECK (jsonb_typeof(lines_json) = 'array'), \n\tFOREIGN KEY(workspace_id) REFERENCES assessment_workspaces (id) ON DELETE CASCADE\n)" )
    op.execute("CREATE TABLE blast_events (\n\tid SERIAL NOT NULL, \n\tworkspace_id INTEGER NOT NULL, \n\tdomain_id VARCHAR(255) NOT NULL, \n\tname VARCHAR(255) NOT NULL, \n\tevent_type VARCHAR(20) NOT NULL, \n\tevent_date DATE, \n\televation_m NUMERIC(12, 3), \n\tblast_block_id INTEGER, \n\tis_archived BOOLEAN NOT NULL, \n\tarchived_at TIMESTAMP WITH TIME ZONE, \n\tarchive_reason TEXT, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_blast_events_workspace_domain_id UNIQUE (workspace_id, domain_id), \n\tCONSTRAINT uq_blast_events_blast_block_id UNIQUE (blast_block_id), \n\tCONSTRAINT ck_blast_events_event_type CHECK (event_type IN ('production', 'contour')), \n\tCONSTRAINT ck_blast_events_block_production_only CHECK (blast_block_id IS NULL OR event_type = 'production'), \n\tFOREIGN KEY(workspace_id) REFERENCES assessment_workspaces (id) ON DELETE CASCADE, \n\tFOREIGN KEY(blast_block_id) REFERENCES blast_blocks (id) ON DELETE SET NULL\n)" )
    op.execute("CREATE TABLE blast_event_geometry_revisions (\n\tid SERIAL NOT NULL, \n\tblast_event_id INTEGER NOT NULL, \n\tdomain_id VARCHAR(255) NOT NULL, \n\trevision_number INTEGER NOT NULL, \n\timported_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tsource_file_name VARCHAR(255) NOT NULL, \n\tsource_geometry_json JSONB NOT NULL, \n\tplan_geometry_json JSONB NOT NULL, \n\televation_m NUMERIC(12, 3), \n\tis_active BOOLEAN NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_blast_event_geometry_revisions_parent_domain_id UNIQUE (blast_event_id, domain_id), \n\tCONSTRAINT uq_blast_event_geometry_revisions_parent_number UNIQUE (blast_event_id, revision_number), \n\tCONSTRAINT ck_blast_event_geometry_revisions_number_positive CHECK (revision_number > 0), \n\tCONSTRAINT ck_blast_event_geometry_revisions_source_array CHECK (jsonb_typeof(source_geometry_json) = 'array'), \n\tCONSTRAINT ck_blast_event_geometry_revisions_plan_object CHECK (jsonb_typeof(plan_geometry_json) = 'object'), \n\tFOREIGN KEY(blast_event_id) REFERENCES blast_events (id) ON DELETE CASCADE\n)" )
    op.execute('CREATE TABLE blast_event_technical_cards (\n\tid SERIAL NOT NULL, \n\tblast_event_id INTEGER NOT NULL, \n\tdomain_id VARCHAR(255) NOT NULL, \n\tis_archived BOOLEAN NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_blast_event_technical_cards_event UNIQUE (blast_event_id), \n\tCONSTRAINT uq_blast_event_technical_cards_domain_id UNIQUE (domain_id), \n\tFOREIGN KEY(blast_event_id) REFERENCES blast_events (id) ON DELETE CASCADE\n)' )
    op.execute("CREATE TABLE blast_event_technical_card_revisions (\n\tid SERIAL NOT NULL, \n\ttechnical_card_id INTEGER NOT NULL, \n\tdomain_id VARCHAR(255) NOT NULL, \n\trevision_number INTEGER NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tblast_event_geometry_revision_id INTEGER NOT NULL, \n\tevent_type VARCHAR(20) NOT NULL, \n\tstatus VARCHAR(20) NOT NULL, \n\tauthor VARCHAR(255), \n\tchange_reason TEXT NOT NULL, \n\tpayload_json JSONB NOT NULL, \n\tis_active BOOLEAN NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_technical_card_revisions_parent_domain_id UNIQUE (technical_card_id, domain_id), \n\tCONSTRAINT uq_technical_card_revisions_parent_number UNIQUE (technical_card_id, revision_number), \n\tCONSTRAINT ck_technical_card_revisions_number_positive CHECK (revision_number > 0), \n\tCONSTRAINT ck_technical_card_revisions_event_type CHECK (event_type IN ('production', 'contour')), \n\tCONSTRAINT ck_technical_card_revisions_status CHECK (status IN ('draft', 'completed')), \n\tCONSTRAINT ck_technical_card_revisions_payload_object CHECK (jsonb_typeof(payload_json) = 'object'), \n\tFOREIGN KEY(technical_card_id) REFERENCES blast_event_technical_cards (id) ON DELETE CASCADE, \n\tFOREIGN KEY(blast_event_geometry_revision_id) REFERENCES blast_event_geometry_revisions (id) ON DELETE RESTRICT\n)" )
    op.execute('CREATE TABLE assessment_areas (\n\tid SERIAL NOT NULL, \n\tworkspace_id INTEGER NOT NULL, \n\tdomain_id VARCHAR(255) NOT NULL, \n\tname VARCHAR(255) NOT NULL, \n\tassessment_date DATE, \n\tis_archived BOOLEAN NOT NULL, \n\tarchived_at TIMESTAMP WITH TIME ZONE, \n\tarchive_reason TEXT, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_assessment_areas_workspace_domain_id UNIQUE (workspace_id, domain_id), \n\tFOREIGN KEY(workspace_id) REFERENCES assessment_workspaces (id) ON DELETE CASCADE\n)' )
    op.execute("CREATE TABLE assessment_area_geometry_revisions (\n\tid SERIAL NOT NULL, \n\tassessment_area_id INTEGER NOT NULL, \n\tdomain_id VARCHAR(255) NOT NULL, \n\trevision_number INTEGER NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tsource_dataset_id INTEGER NOT NULL, \n\tselection_polygon_json JSONB NOT NULL, \n\tfinal_geometry_json JSONB NOT NULL, \n\tlower_elevation_m NUMERIC(12, 3) NOT NULL, \n\tupper_elevation_m NUMERIC(12, 3) NOT NULL, \n\thorizon_slices_json JSONB NOT NULL, \n\tchange_reason TEXT NOT NULL, \n\tis_active BOOLEAN NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_assessment_area_geometry_revisions_parent_domain_id UNIQUE (assessment_area_id, domain_id), \n\tCONSTRAINT uq_assessment_area_geometry_revisions_parent_number UNIQUE (assessment_area_id, revision_number), \n\tCONSTRAINT ck_assessment_area_geometry_revisions_number_positive CHECK (revision_number > 0), \n\tCONSTRAINT ck_assessment_area_geometry_revisions_elevation_order CHECK (lower_elevation_m < upper_elevation_m), \n\tCONSTRAINT ck_assessment_area_geometry_revisions_selection_object CHECK (jsonb_typeof(selection_polygon_json) = 'object'), \n\tCONSTRAINT ck_assessment_area_geometry_revisions_final_object CHECK (jsonb_typeof(final_geometry_json) = 'object'), \n\tCONSTRAINT ck_assessment_area_geometry_revisions_slices_array CHECK (jsonb_typeof(horizon_slices_json) = 'array'), \n\tFOREIGN KEY(assessment_area_id) REFERENCES assessment_areas (id) ON DELETE CASCADE, \n\tFOREIGN KEY(source_dataset_id) REFERENCES project_lines_datasets (id) ON DELETE RESTRICT\n)" )
    op.execute("CREATE TABLE assessment_event_links (\n\tid SERIAL NOT NULL, \n\tassessment_area_geometry_revision_id INTEGER NOT NULL, \n\tblast_event_geometry_revision_id INTEGER NOT NULL, \n\tdomain_id VARCHAR(255) NOT NULL, \n\tstatus VARCHAR(20) NOT NULL, \n\tsource VARCHAR(20) NOT NULL, \n\tfrozen_intersection_geometry_json JSONB, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_assessment_event_links_parent_domain_id UNIQUE (assessment_area_geometry_revision_id, domain_id), \n\tCONSTRAINT uq_assessment_event_links_geometry_source UNIQUE (assessment_area_geometry_revision_id, blast_event_geometry_revision_id, source), \n\tCONSTRAINT ck_assessment_event_links_status CHECK (status IN ('suggested', 'confirmed', 'excluded')), \n\tCONSTRAINT ck_assessment_event_links_source CHECK (source IN ('automatic', 'manual')), \n\tCONSTRAINT ck_assessment_event_links_frozen_object CHECK (frozen_intersection_geometry_json IS NULL OR jsonb_typeof(frozen_intersection_geometry_json) = 'object'), \n\tFOREIGN KEY(assessment_area_geometry_revision_id) REFERENCES assessment_area_geometry_revisions (id) ON DELETE CASCADE, \n\tFOREIGN KEY(blast_event_geometry_revision_id) REFERENCES blast_event_geometry_revisions (id) ON DELETE RESTRICT\n)" )
    op.execute('CREATE TABLE assessment_area_evaluations (\n\tid SERIAL NOT NULL, \n\tassessment_area_id INTEGER NOT NULL, \n\tdomain_id VARCHAR(255) NOT NULL, \n\tis_archived BOOLEAN NOT NULL, \n\tarchived_at TIMESTAMP WITH TIME ZONE, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_assessment_area_evaluations_area UNIQUE (assessment_area_id), \n\tFOREIGN KEY(assessment_area_id) REFERENCES assessment_areas (id) ON DELETE CASCADE\n)' )
    op.execute("CREATE TABLE assessment_area_evaluation_revisions (\n\tid SERIAL NOT NULL, \n\tevaluation_id INTEGER NOT NULL, \n\tdomain_id VARCHAR(255) NOT NULL, \n\trevision_number INTEGER NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tassessment_area_geometry_revision_id INTEGER NOT NULL, \n\tassessment_date DATE, \n\tinspector VARCHAR(255) NOT NULL, \n\tstatus VARCHAR(20) NOT NULL, \n\tmatrix_template_id VARCHAR(255) NOT NULL, \n\tmatrix_template_version INTEGER NOT NULL, \n\tdesign_achievement_index NUMERIC(8, 6), \n\tface_condition_index NUMERIC(8, 6), \n\tresult_quadrant VARCHAR(80), \n\tpayload_json JSONB NOT NULL, \n\tis_active BOOLEAN NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_assessment_evaluation_revisions_parent_domain_id UNIQUE (evaluation_id, domain_id), \n\tCONSTRAINT uq_assessment_evaluation_revisions_parent_number UNIQUE (evaluation_id, revision_number), \n\tCONSTRAINT ck_assessment_evaluation_revisions_number_positive CHECK (revision_number > 0), \n\tCONSTRAINT ck_assessment_evaluation_revisions_template_version_positive CHECK (matrix_template_version > 0), \n\tCONSTRAINT ck_assessment_evaluation_revisions_status CHECK (status IN ('draft', 'completed')), \n\tCONSTRAINT ck_assessment_evaluation_revisions_design_index CHECK (design_achievement_index IS NULL OR design_achievement_index BETWEEN 0 AND 1), \n\tCONSTRAINT ck_assessment_evaluation_revisions_face_index CHECK (face_condition_index IS NULL OR face_condition_index BETWEEN 0 AND 1), \n\tCONSTRAINT ck_assessment_evaluation_revisions_payload_object CHECK (jsonb_typeof(payload_json) = 'object'), \n\tFOREIGN KEY(evaluation_id) REFERENCES assessment_area_evaluations (id) ON DELETE CASCADE, \n\tFOREIGN KEY(assessment_area_geometry_revision_id) REFERENCES assessment_area_geometry_revisions (id) ON DELETE RESTRICT\n)" )
    op.execute("CREATE TABLE assessment_entity_attachments (\n\tid SERIAL NOT NULL, \n\tdomain_id VARCHAR(255) NOT NULL, \n\towner_type VARCHAR(30) NOT NULL, \n\tblast_event_id INTEGER, \n\tassessment_area_evaluation_id INTEGER, \n\tattachment_kind VARCHAR(20) NOT NULL, \n\tsubtype VARCHAR(80), \n\tcustom_subtype VARCHAR(255), \n\ttitle VARCHAR(255), \n\toriginal_filename VARCHAR(255) NOT NULL, \n\tstored_filename VARCHAR(255) NOT NULL, \n\trelative_path VARCHAR(1024) NOT NULL, \n\tfile_date DATE, \n\tdescription TEXT, \n\tmime_type VARCHAR(255), \n\tfile_size_bytes BIGINT, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_assessment_entity_attachments_domain_id UNIQUE (domain_id), \n\tCONSTRAINT ck_assessment_entity_attachments_owner CHECK ((owner_type = 'blast_event' AND blast_event_id IS NOT NULL AND assessment_area_evaluation_id IS NULL) OR (owner_type = 'assessment_evaluation' AND assessment_area_evaluation_id IS NOT NULL AND blast_event_id IS NULL)), \n\tCONSTRAINT ck_assessment_entity_attachments_kind CHECK (attachment_kind IN ('photo', 'document')), \n\tCONSTRAINT ck_assessment_entity_attachments_file_size CHECK (file_size_bytes IS NULL OR file_size_bytes >= 0), \n\tCONSTRAINT ck_assessment_entity_attachments_relative_path CHECK (length(btrim(relative_path)) > 0), \n\tFOREIGN KEY(blast_event_id) REFERENCES blast_events (id) ON DELETE CASCADE, \n\tFOREIGN KEY(assessment_area_evaluation_id) REFERENCES assessment_area_evaluations (id) ON DELETE CASCADE\n)" )
    op.create_index('ix_project_lines_datasets_workspace_id', 'project_lines_datasets', ['workspace_id'])
    op.create_index('ix_project_lines_datasets_imported_at', 'project_lines_datasets', ['imported_at'])
    op.create_index('ix_project_lines_datasets_one_active_per_workspace', 'project_lines_datasets', ['workspace_id'], unique=True, postgresql_where=sa.text('is_active'))
    op.create_index('ix_blast_events_event_type', 'blast_events', ['event_type'])
    op.create_index('ix_blast_events_event_date', 'blast_events', ['event_date'])
    op.create_index('ix_blast_events_is_archived', 'blast_events', ['is_archived'])
    op.create_index('ix_blast_events_workspace_id', 'blast_events', ['workspace_id'])
    op.create_index('ix_blast_events_elevation_m', 'blast_events', ['elevation_m'])
    op.create_index('ix_blast_event_geometry_revisions_one_active', 'blast_event_geometry_revisions', ['blast_event_id'], unique=True, postgresql_where=sa.text('is_active'))
    op.create_index('ix_technical_card_revisions_one_active', 'blast_event_technical_card_revisions', ['technical_card_id'], unique=True, postgresql_where=sa.text('is_active'))
    op.create_index('ix_assessment_areas_workspace_id', 'assessment_areas', ['workspace_id'])
    op.create_index('ix_assessment_areas_assessment_date', 'assessment_areas', ['assessment_date'])
    op.create_index('ix_assessment_areas_is_archived', 'assessment_areas', ['is_archived'])
    op.create_index('ix_assessment_area_geometry_revisions_one_active', 'assessment_area_geometry_revisions', ['assessment_area_id'], unique=True, postgresql_where=sa.text('is_active'))
    op.create_index('ix_assessment_event_links_area_geometry_revision_id', 'assessment_event_links', ['assessment_area_geometry_revision_id'])
    op.create_index('ix_assessment_event_links_blast_geometry_revision_id', 'assessment_event_links', ['blast_event_geometry_revision_id'])
    op.create_index('ix_assessment_event_links_status', 'assessment_event_links', ['status'])
    op.create_index('ix_assessment_evaluation_revisions_one_active', 'assessment_area_evaluation_revisions', ['evaluation_id'], unique=True, postgresql_where=sa.text('is_active'))
    op.create_index('ix_assessment_entity_attachments_kind', 'assessment_entity_attachments', ['attachment_kind'])
    op.create_index('ix_assessment_entity_attachments_blast_event_id', 'assessment_entity_attachments', ['blast_event_id'])
    op.create_index('ix_assessment_entity_attachments_evaluation_id', 'assessment_entity_attachments', ['assessment_area_evaluation_id'])
    op.create_index('ix_assessment_entity_attachments_file_date', 'assessment_entity_attachments', ['file_date'])


def downgrade() -> None:
    op.drop_index('ix_assessment_entity_attachments_file_date', table_name='assessment_entity_attachments')
    op.drop_index('ix_assessment_entity_attachments_evaluation_id', table_name='assessment_entity_attachments')
    op.drop_index('ix_assessment_entity_attachments_blast_event_id', table_name='assessment_entity_attachments')
    op.drop_index('ix_assessment_entity_attachments_kind', table_name='assessment_entity_attachments')
    op.drop_index('ix_assessment_evaluation_revisions_one_active', table_name='assessment_area_evaluation_revisions')
    op.drop_index('ix_assessment_event_links_status', table_name='assessment_event_links')
    op.drop_index('ix_assessment_event_links_blast_geometry_revision_id', table_name='assessment_event_links')
    op.drop_index('ix_assessment_event_links_area_geometry_revision_id', table_name='assessment_event_links')
    op.drop_index('ix_assessment_area_geometry_revisions_one_active', table_name='assessment_area_geometry_revisions')
    op.drop_index('ix_assessment_areas_is_archived', table_name='assessment_areas')
    op.drop_index('ix_assessment_areas_assessment_date', table_name='assessment_areas')
    op.drop_index('ix_assessment_areas_workspace_id', table_name='assessment_areas')
    op.drop_index('ix_technical_card_revisions_one_active', table_name='blast_event_technical_card_revisions')
    op.drop_index('ix_blast_event_geometry_revisions_one_active', table_name='blast_event_geometry_revisions')
    op.drop_index('ix_blast_events_elevation_m', table_name='blast_events')
    op.drop_index('ix_blast_events_workspace_id', table_name='blast_events')
    op.drop_index('ix_blast_events_is_archived', table_name='blast_events')
    op.drop_index('ix_blast_events_event_date', table_name='blast_events')
    op.drop_index('ix_blast_events_event_type', table_name='blast_events')
    op.drop_index('ix_project_lines_datasets_one_active_per_workspace', table_name='project_lines_datasets')
    op.drop_index('ix_project_lines_datasets_imported_at', table_name='project_lines_datasets')
    op.drop_index('ix_project_lines_datasets_workspace_id', table_name='project_lines_datasets')
    op.drop_table('assessment_entity_attachments')
    op.drop_table('assessment_area_evaluation_revisions')
    op.drop_table('assessment_area_evaluations')
    op.drop_table('assessment_event_links')
    op.drop_table('assessment_area_geometry_revisions')
    op.drop_table('assessment_areas')
    op.drop_table('blast_event_technical_card_revisions')
    op.drop_table('blast_event_technical_cards')
    op.drop_table('blast_event_geometry_revisions')
    op.drop_table('blast_events')
    op.drop_table('project_lines_datasets')
    op.drop_table('assessment_workspaces')
