"""Focused write boundary for Assessment commands (Phase 5B)."""
from __future__ import annotations

from typing import Protocol
from application.ports.domain_version import DomainWriteResult

from domain.assessment.entities import AssessmentArea
from domain.assessment.evaluation import AssessmentAreaEvaluation
from domain.attachments.entities import EntityAttachment
from domain.blasting.entities import BlastEvent, BlastEventGeometryRevision
from domain.blasting.technical_card import (
    BlastEventTechnicalCard, BlastEventTechnicalCardRevision,
)
from domain.wall_conformance import WallAlignment


class AssessmentWrites(Protocol):
    """Explicit writes; deliberately no whole-aggregate ``save`` operation."""

    def persist_area_archive(self, domain_id: int, expected_version: int, area: AssessmentArea) -> DomainWriteResult: ...
    def persist_contour_archive(self, domain_id: int, expected_version: int, event: BlastEvent) -> DomainWriteResult: ...
    def update_contour_metadata(self, domain_id: int, expected_version: int,
            target_domain_id: int, target_expected_version: int, event_id: str,
            name: str, elevation: float) -> DomainWriteResult: ...
    def update_assessment_area_metadata(self, domain_id: int, expected_version: int,
            target_domain_id: int, target_expected_version: int, area_id: str,
            name: str) -> DomainWriteResult: ...
    def append_blast_geometry_revision(self, domain_id: int, expected_version: int,
                                       event_id: str, revision: BlastEventGeometryRevision) -> DomainWriteResult: ...
    def persist_technical_card_revision(self, domain_id: int,
            expected_version: int, card: BlastEventTechnicalCard,
            revision: BlastEventTechnicalCardRevision, event_date) -> DomainWriteResult: ...
    def persist_assessment_area_geometry(self, domain_id: int,
                                         expected_version: int, area: AssessmentArea) -> DomainWriteResult: ...
    def load_wall_alignment(self, domain_id: int, area_id: str,
                            geometry_revision_id: str) -> WallAlignment | None: ...
    def save_wall_alignment(self, domain_id: int, expected_version: int, area_id: str,
                            geometry_revision_id: str, alignment: WallAlignment) -> DomainWriteResult: ...
    def clear_wall_alignment(self, domain_id: int, expected_version: int, area_id: str,
                             geometry_revision_id: str) -> DomainWriteResult: ...
    def synchronize_area_links(self, domain_id: int, expected_version: int, area: AssessmentArea) -> DomainWriteResult: ...
    def persist_evaluation_owner(self, domain_id: int,
                                 expected_version: int, evaluation: AssessmentAreaEvaluation) -> DomainWriteResult: ...
    def persist_evaluation_revision(self, domain_id: int,
            expected_version: int, evaluation: AssessmentAreaEvaluation, revision) -> DomainWriteResult: ...
    def add_attachment_metadata_batch(self, domain_id: int,
            expected_version: int, attachments: list[EntityAttachment],
            evaluation_owner: AssessmentAreaEvaluation | None = None) -> DomainWriteResult: ...
    def update_attachment_metadata(self, domain_id: int,
                                   expected_version: int, attachment: EntityAttachment) -> DomainWriteResult: ...
    def delete_attachment_metadata(self, domain_id: int, expected_version: int, attachment_id: str) -> DomainWriteResult: ...
