from typing import Protocol
from domain.blasting.charge_presets import ChargeDesignPreset

class ChargePresetRepository(Protocol):
    def list_for_site(self, site_id: int) -> list[ChargeDesignPreset]: ...
    def create(self, preset: ChargeDesignPreset) -> ChargeDesignPreset: ...
    def update(self, preset: ChargeDesignPreset) -> ChargeDesignPreset: ...
    def delete(self, preset_id: int, site_id: int) -> None: ...
