from typing import Protocol
from domain.blasting.charge_design import ChargeDesignPreset, ChargePresetComponent


class ChargePresetPersistence(Protocol):
    def list_presets(self, site_id: int) -> list[ChargeDesignPreset]: ...
    def create_preset(self, site_id: int, name: str, components: tuple[ChargePresetComponent, ...]) -> ChargeDesignPreset: ...
    def update_preset(self, preset_id: int, site_id: int, name: str, components: tuple[ChargePresetComponent, ...]) -> ChargeDesignPreset: ...
    def delete_preset(self, preset_id: int, site_id: int) -> None: ...
