from __future__ import annotations

from typing import Protocol
from domain.blasting.charge_design import ExplosiveProduct


class ExplosiveCatalogueQueries(Protocol):
    def list_products(self, *, enabled_only: bool = False) -> list[ExplosiveProduct]: ...
    def get_product(self, product_id: int) -> ExplosiveProduct | None: ...


class ExplosiveCatalogueWrites(Protocol):
    def create_product(self, product: ExplosiveProduct) -> ExplosiveProduct: ...
    def update_product(self, product: ExplosiveProduct) -> ExplosiveProduct: ...
    def set_product_enabled(self, product_id: int, enabled: bool) -> ExplosiveProduct: ...
